version: '3.1'

services:

  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    network_mode: bridge
    container_name: postgres

    environment:
      POSTGRES_USER: tyrell
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: playerStats
    